{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "loginform.resourceName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{ include "loginform.labels" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "loginform.resourceName" . }}
                port:
                  number: 80
{{- end }}

