apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "loginform.resourceName" . }}
  labels:
    {{ include "loginform.labels" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.containerPort }}
  selector:
    {{ include "loginform.labels" . }}
